### ISSUE TITLE
AssertionError when decrypting 

### ISSUE THREAD

**Issue by Viarmin** [tlambertz/seedvault_backup_parser#11]
I'm trying to decrypt a SeedVault backup on Windows 10/x64 . Here's my command:

> parse.py decrypt 1615637348786 decrypted

keep getting AssertionError:

> Decrypting Key-Value files:
>   for app kv\@pm@
> Traceback (most recent call last):
>   File "F:\Programms\python\parse.py", line 389, in <module>
>     main()
>   File "F:\Programms\python\parse.py", line 378, in main
>     kv_parsed = parse_backup(backupfolder, targetfolder, userkey)
>   File "F:\Programms\python\parse.py", line 169, in parse_backup
>     kv_parsed = parse_kv_backup(backupfolder, targetfolder, key)
>   File "F:\Programms\python\parse.py", line 77, in parse_kv_backup
>     assert versionheader['name'].decode() == appname
> AssertionError

 i could´t resolve my issue from #7 as i don´t specified absolute paths.
What else could i do?

**Comment by ghost** [comment]
I get the error also, independently if I run the script with absolut or relative paths (even if copy the script in the seedvault directory).

**Comment by jtagcat** [comment]
Duplicate of https://github.com/tlambertz/seedvault_backup_parser/issues/14
