### ISSUE TITLE
AssertionError when decrypting

### ISSUE THREAD

**Issue by laurastephsmith** [tlambertz/seedvault_backup_parser#7]
I'm trying to decrypt a SeedVault backup on Ubuntu running in WSL. Here's my command:
```
laura@lauralaptop:~/android/seedvault_backup_parser$ ./parse.py decrypt /mnt/c/Users/laura/Dropbox/Backup/Fairphone/.See
dVaultAndroidBackup/1614124366878 tempdecrypted
```
It finds the list of APKs, then gives this error:
```
Decrypting Key-Value files:
  for app c/Users/laura/Dropbox/Backup/Fairphone/.SeedVaultAndroidBackup/1614124366878/kv/@pm@
Traceback (most recent call last):
  File "./parse.py", line 376, in <module>
    main()
  File "./parse.py", line 365, in main
    kv_parsed = parse_backup(backupfolder, targetfolder, userkey)
  File "./parse.py", line 156, in parse_backup
    kv_parsed = parse_kv_backup(backupfolder, targetfolder, key)
  File "./parse.py", line 64, in parse_kv_backup
    assert versionheader['name'].decode() == appname
AssertionError
```
Any help would be appreciated!

**Comment by tlambertz** [comment]
Absolute paths were not supported previously. @Whisprin fixed this in https://github.com/tlambertz/seedvault_backup_parser/pull/6, so it should work now if you update.

**Comment by laurastephsmith** [comment]
Wonderful, thank you, works perfectly!
